name: Run tests
on: [ push ]
jobs:
  run-solution-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Write secrets to file
        run: |
          echo "SECRET_1=${{ secrets._2024_1 }}" >> ./src/test/resources/2024/1.txt
          # Add more secrets as needed
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./gradlew clean build

